version: "3.7"
services:
  janus:
    image: janusgraph/janusgraph
    volumes:
      - "./gremlin-server.yaml:/opt/janusgraph/conf/gremlin-server/gremlin-server.yaml"
      - "./sample.groovy:/opt/janusgraph/scripts/sample.groovy"

  app:
    image: localhost:5000/janus-app
    build:
      context: app/
      dockerfile: ../Dockerfile
    entrypoint: ["go"]
    working_dir: /home/app
    volumes:
      - "./app:/home/app"
    command:
      - run
      - main.go
      - -h
      - ws://janus:8182
      - -d
      - "30"
    depends_on:
      - janus
