version: "3.7"
services:
  janus:
    image: janusgraph/janusgraph
    volumes:
      - "./gremlin-server.yaml:/opt/janusgraph/conf/gremlin-server/gremlin-server.yaml"
      - "./indexless.groovy:/opt/janusgraph/scripts/sample.groovy"

  app:
    image: golang:1.14-buster
    entrypoint: ["go"]
    working_dir: /home/app
    volumes:
      - "./app:/home/app"
    command:
      - run
      - main.go
      - -h
      - ws://janus:8182
      - -d
      - "60"
    depends_on:
      - janus
